version: '2'
services:
  mysql:
    restart: always
    build: ./data/mysql/
    volumes:
      - "./data/mysql/db:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: my_app
      MYSQL_PASSWORD: secret
      MYSQL_DATABASE: my_app
      TZ: "Asia/Tokyo"
    ports:
      - "13307:3306"
  host:
    build: ./data/htdocs
    environment:
      TZ: "Asia/Tokyo"
      PRJ: "weather_app"
      MYSQL_HOST: "mysql"
      MYSQL_USER: "my_app"
      MYSQL_PASSWORD: "secret"
      MYSQL_DATABASE: "weather_app"
    volumes:
      - "./data/htdocs:/root"
    ports:
      - "18765:80"
    depends_on:
      - mysql
  phpmyadmin:
    build: ./data/phpmyadmin
    environment:
      PMA_ARBITRARY: 1
      PMA_HOSTS: weather_app_mysql_1
      PMA_USER: root
      PMA_PASSWORD: password
    ports:
      - 18080:80
    depends_on:
      - mysql
  flask:
    build: ./data/flask/
    volumes:
      - ./data/flask:/api
    ports:
      - "5001:5000"
    command: flask run --host 0.0.0.0 --port 5000