apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    run: host
  name: host
spec:
  replicas: 1
  selector:
    matchLabels:
      run: host
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: host
    spec:
      containers:
        - env:
            - name: PRJ
              valueFrom:
                configMapKeyRef:
                  name: my-config
                  key: prj
            - name: TZ
              valueFrom:
                configMapKeyRef:
                  name: my-config
                  key: tz
            - name: MYSQL_HOST
              valueFrom:
                configMapKeyRef:
                  name: my-config
                  key: mysql_host
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: my-config
                  key: mysql_database
            - name: MYSQL_USER
              valueFrom:
                configMapKeyRef:
                  name: my-config
                  key: mysql_user
            - name: MYSQL_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: my-config
                  key: mysql_password
          image: fyomaruhauto1212/weather_app_host
          name: host
          ports:
            - containerPort: 80
          resources: {}
      restartPolicy: Always
status: {}