apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    run: phpmyadmin
  name: phpmyadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      run: phpmyadmin
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: phpmyadmin
    spec:
      containers:
        - env:
            - name: PMA_ARBITRARY
              valueFrom:
                configMapKeyRef:
                  name: my-config
                  key: pma_arbitrary
            - name: PMA_HOSTS
              valueFrom:
                configMapKeyRef:
                  name: my-config
                  key: pma_hosts
            - name: PMA_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: my-config
                  key: pma_password
            - name: PMA_USER
              valueFrom:
                configMapKeyRef:
                  name: my-config
                  key: pma_user
          image: fyomaruhauto1212/weather_app_phpmyadmin
          name: phpmyadmin
          ports:
            - containerPort: 80
          resources: {}
      restartPolicy: Always
status: {}
